In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("spam.csv",encoding='ISO-8859-1')
df.head(5)

,category,message,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN

In [3]:
new_df=[feature for feature in df.columns if df[feature].isnull().sum()]
new_df

['Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4']

In [ ]:
df.drop(new_df,axis=1,inplace=True)

In [6]:
df

     category                                            message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham              Will Ì_ b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [11]:
def new_col(x):
    if x=="spam":
        return 1
    return 0

In [12]:
df["spam"]=df["category"].apply(new_col)

In [13]:
df

     category                                            message  spam
0         ham  Go until jurong point, crazy.. Available only ...     0
1         ham                      Ok lar... Joking wif u oni...     0
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3         ham  U dun say so early hor... U c already then say...     0
4         ham  Nah I don't think he goes to usf, he lives aro...     0
...       ...                                                ...   ...
5567     spam  This is the 2nd time we have tried 2 contact u...     1
5568      ham              Will Ì_ b going to esplanade fr home?     0
5569      ham  Pity, * was in mood for that. So...any other s...     0
5570      ham  The guy did some bitching but I acted like i'd...     0
5571      ham                         Rofl. Its true to its name     0

[5572 rows x 3 columns]

In [8]:
df

     category                                            message  spam
0         ham  Go until jurong point, crazy.. Available only ...     0
1         ham                      Ok lar... Joking wif u oni...     0
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3         ham  U dun say so early hor... U c already then say...     0
4         ham  Nah I don't think he goes to usf, he lives aro...     0
...       ...                                                ...   ...
5567     spam  This is the 2nd time we have tried 2 contact u...     1
5568      ham              Will Ì_ b going to esplanade fr home?     0
5569      ham  Pity, * was in mood for that. So...any other s...     0
5570      ham  The guy did some bitching but I acted like i'd...     0
5571      ham                         Rofl. Its true to its name     0

[5572 rows x 3 columns]

In [17]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(df.message,df.spam,test_size=.3)

In [18]:
from sklearn.feature_extraction.text import CountVectorizer

v=CountVectorizer()

X_train_cv=v.fit_transform(X_train.values)
X_train_cv

<3900x7243 sparse matrix of type '<class 'numpy.int64'>'
	with 52053 stored elements in Compressed Sparse Row format>

In [19]:
X_train_cv.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [20]:
X_train.values

array(['Will be office around 4 pm. Now i am going hospital.',
       'Thats a bit weird, even ?- where is the do supposed to be happening? But good idea, sure they will be in pub!',
       'Sweetheart, hope you are not having that kind of day! Have one with loads of reasons to smile. Biola',
       ..., 'Some are lasting as much as 2 hours. You might get lucky.',
       "INTERFLORA - åÒIt's not too late to order Interflora flowers for christmas call 0800 505060 to place your order before Midnight tomorrow.",
       '2marrow only. Wed at  &lt;#&gt;  to 2 aha.'], dtype=object)

In [21]:
X_train_np=X_train_cv.toarray()
X_train_np[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [23]:
v.vocabulary_

{'will': 7007,
 'be': 1177,
 'office': 4565,
 'around': 988,
 'pm': 4896,
 'now': 4513,
 'am': 859,
 'going': 2958,
 'hospital': 3261,
 'thats': 6356,
 'bit': 1265,
 'weird': 6946,
 'even': 2482,
 'where': 6977,
 'is': 3487,
 'the': 6358,
 'do': 2216,
 'supposed': 6167,
 'to': 6470,
 'happening': 3099,
 'but': 1464,
 'good': 2969,
 'idea': 3343,
 'sure': 6171,
 'they': 6380,
 'in': 3385,
 'pub': 5105,
 'sweetheart': 6200,
 'hope': 3247,
 'you': 7186,
 'are': 970,
 'not': 4500,
 'having': 3132,
 'that': 6353,
 'kind': 3669,
 'of': 4558,
 'day': 2032,
 'have': 3126,
 'one': 4601,
 'with': 7034,
 'loads': 3869,
 'reasons': 5221,
 'smile': 5818,
 'biola': 1256,
 'got': 2984,
 'it': 3497,
 'seventeen': 5626,
 'pounds': 4969,
 'for': 2745,
 'seven': 5625,
 'hundred': 3307,
 'ml': 4212,
 'ûò': 7241,
 'ok': 4581,
 'knw': 3692,
 'dis': 2183,
 'no': 4466,
 'lt': 3951,
 'gt': 3033,
 'll': 3865,
 'get': 2906,
 'there': 6374,
 'at': 1028,
 'unless': 6687,
 'guys': 3053,
 'want': 6876,
 'me': 4102,
 'come': 1778,
 'some': 5860,
 'time': 6440,
 'sooner': 5885,
 'new': 4434,
 'textbuddy': 6333,
 'chat': 1629,
 'horny': 3257,
 'ur': 6716,
 'area': 971,
 'just': 3609,
 '25p': 350,
 'free': 2783,
 'receive': 5232,
 'search': 5555,
 'postcode': 4959,
 'or': 4632,
 'gaytextbuddy': 2881,
 'com': 1773,
 'txt': 6620,
 'name': 4369,
 '89693': 655,
 'dont': 2248,
 'message': 4144,
 'offer': 4563,
 'and': 882,
 'also': 852,
 've': 6769,
 'sorta': 5895,
 'blown': 1300,
 'him': 3196,
 'off': 4560,
 'couple': 1900,
 'times': 6441,
 'recently': 5237,
 'so': 5846,
 'id': 3342,
 'rather': 5183,
 'text': 6329,
 'out': 4662,
 'blue': 1302,
 'looking': 3901,
 'weed': 6936,
 'sound': 5902,
 'like': 3820,
 'manky': 4046,
 'scouse': 5540,
 'boy': 1366,
 'steve': 6031,
 'travelling': 6558,
 'on': 4595,
 'da': 1993,
 'bus': 1457,
 'home': 3232,
 'wot': 7094,
 'has': 3113,
 'inmind': 3428,
 'recreation': 5251,
 'eve': 2480,
 'emigrated': 2402,
 'something': 5869,
 'maybe': 4096,
 '30': 398,
 'was': 6890,
 'hopeful': 3249,
 'buy': 1469,
 'mum': 4325,
 'present': 5016,
 'ar': 964,
 'well': 6952,
 'its': 3503,
 'actually': 740,
 'called': 1502,
 'someone': 5864,
 'punto': 5112,
 'woulda': 7098,
 'been': 1195,
 'worse': 7091,
 'jamster': 3527,
 'your': 7191,
 'wallpaper': 6868,
 'heart': 3150,
 '88888': 649,
 'apply': 945,
 '16': 300,
 'only': 4606,
 'need': 4405,
 'help': 3166,
 'call': 1496,
 '08701213186': 69,
 'bill': 1250,
 '33': 414,
 '65': 534,
 'bad': 1104,
 'cant': 1532,
 'believe': 1212,
 'said': 5470,
 'many': 4048,
 'things': 6385,
 'this': 6393,
 'morning': 4273,
 'when': 6973,
 'all': 837,
 'really': 5216,
 'wanted': 6878,
 'say': 5516,
 'love': 3930,
 'beautiful': 1182,
 'see': 5571,
 'library': 3806,
 'later': 3746,
 'stupid': 6100,
 'possible': 4954,
 'pls': 4888,
 'stop': 6048,
 'bootydelious': 1331,
 '32': 409,
 'inviting': 3468,
 'her': 3174,
 'friend': 2801,
 'reply': 5313,
 'yes': 7170,
 '434': 454,
 'www': 7125,
 'sms': 5827,
 'ac': 703,
 'send': 5594,
 'frnd': 2809,
 '62468': 530,
 'hmm': 3212,
 'too': 6502,
 'them': 6366,
 'unfortunately': 6674,
 'pics': 4844,
 'obviously': 4549,
 'arent': 973,
 'hot': 3266,
 'cakes': 1489,
 'kinda': 3670,
 'fun': 2835,
 'tho': 6399,
 'what': 6966,
 'pin': 4855,
 'aathi': 683,
 'lot': 3917,
 'last': 3740,
 'chance': 1609,
 'claim': 1701,
 '150': 289,
 'worth': 7093,
 'discount': 2192,
 'vouchers': 6828,
 'today': 6475,
 'shop': 5690,
 '85023': 624,
 'savamob': 5510,
 'offers': 4564,
 'mobile': 4226,
 'cs': 1952,
 'pobox84': 4908,
 'm263uz': 3982,
 '00': 0,
 'sub': 6105,
 '123': 271,
 'congratulations': 1835,
 'week': 6937,
 'competition': 1797,
 'draw': 2275,
 'won': 7063,
 '1450': 285,
 'prize': 5048,
 '09050002311': 158,
 'b4280703': 1089,
 '08718727868': 138,
 'over': 4676,
 '18': 304,
 '150ppm': 294,
 'give': 2932,
 'prometazine': 5075,
 'syrup': 6218,
 '5mls': 514,
 'then': 6370,
 'mins': 4182,
 'feed': 2621,
 'urgent': 6720,
 '07808726822': 35,
 'awarded': 1079,
 '000': 1,
 'bonus': 1319,
 'caller': 1503,
 '02': 7,
 '09': 151,
 '03': 12,
 'our': 4659,
 '2nd': 381,
 'attempt': 1039,
 'contact': 1847,
 '0871': 87,
 '872': 639,
 '9758': 667,
 'box95qu': 1364,
 'back': 1101,
 'amp': 871,
 'we': 6917,
 're': 5197,
 'packing': 4695,
 'car': 1539,
 'let': 3798,
 'know': 3688,
 'if': 3352,
 'room': 5409,
 'gr8': 2995,
 'leaving': 3778,
 'congrats': 1833,
 'dear': 2043,
 'school': 5531,
 'wat': 6897,
 'plans': 4872,
 'slowly': 5807,
 'god': 2952,
 'clean': 1711,
 'my': 4349,
 'blood': 1296,
 'ten': 6307,
 'special': 5926,
 'people': 4787,
 'miracle': 4186,
 'tomorrow': 6492,
 'todays': 6476,
 'vodafone': 6816,
 'numbers': 4527,
 'ending': 2412,
 '4882': 469,
 'selected': 5581,
 '350': 416,
 'award': 1078,
 'number': 4526,
 'matches': 4076,
 '09064019014': 208,
 'girl': 2926,
 'does': 2225,
 'stay': 6013,
 'bed': 1191,
 'doesn': 2226,
 'recovery': 5249,
 'pass': 4741,
 'while': 6982,
 'cooped': 1873,
 'up': 6701,
 'enjoy': 2424,
 'watching': 6902,
 'playing': 4879,
 'football': 2742,
 'basketball': 1149,
 'anything': 923,
 'outdoors': 4665,
 'oooh': 4612,
 'plenty': 4886,
 'those': 6400,
 'normally': 4494,
 'use': 6730,
 'drink': 2283,
 'more': 4269,
 'water': 6904,
 'daily': 2001,
 '500': 494,
 'msgs': 4306,
 '80488': 592,
 'credit': 1930,
 'account': 717,
 '645': 533,
 'bahamas': 1110,
 'callfreefone': 1506,
 '08081560665': 57,
 'speak': 5924,
 'live': 3857,
 'operator': 4621,
 'either': 2383,
 'cruise': 1948,
 'ofå': 4573,
 '2000': 327,
 'cash': 1566,
 'opt': 4627,
 '07786200117': 31,
 'would': 7097,
 'fuckin': 2825,
 'didnt': 2148,
 'had': 3061,
 'thurs': 6422,
 'pre': 4999,
 'booked': 1322,
 'cancelled': 1526,
 'again': 787,
 'needs': 4410,
 'sacked': 5461,
 'next': 4441,
 'amazing': 860,
 'xxx': 7141,
 'picsfree1': 4845,
 'video': 6787,
 'sent': 5604,
 'vid': 6786,
 'enough': 2430,
 '2day': 363,
 'keyword': 3653,
 'he': 3137,
 'gonna': 2967,
 'worry': 7089,
 'nothing': 4504,
 'money': 4253,
 'necklace': 4403,
 'as': 1001,
 'token': 6482,
 'wife': 6999,
 'liking': 3824,
 'can': 1520,
 'wait': 6854,
 'till': 6439,
 'valued': 6758,
 'customer': 1980,
 'pleased': 4882,
 'advise': 767,
 'following': 2731,
 'recent': 5236,
 'review': 5361,
 'mob': 4225,
 '1500': 290,
 '09066368470': 225,
 'by': 1479,
 'march': 4051,
 'should': 5703,
 'ready': 5208,
 'problem': 5054,
 'capital': 1536,
 'never': 4430,
 'complete': 1803,
 'how': 3279,
 'far': 2593,
 'work': 7078,
 'ladies': 3716,
 'haha': 3064,
 'okay': 4582,
 'weekend': 6939,
 'leh': 3786,
 'gent': 2897,
 'trying': 6590,
 'weekends': 6940,
 'shows': 5716,
 '1000': 248,
 'guaranteed': 3036,
 '09064012160': 204,
 'code': 1753,
 'k52': 3615,
 'valid': 6754,
 '12hrs': 276,
 'nope': 4486,
 'tv': 6611,
 'bored': 1333,
 'fantasy': 2592,
 'go': 2946,
 'sky': 5781,
 'gamestar': 2861,
 'active': 736,
 'play': 4874,
 '250k': 349,
 'dream': 2277,
 'team': 6279,
 'scoring': 5536,
 'starts': 6005,
 'saturday': 5508,
 'register': 5271,
 '88088': 645,
 'aiyar': 816,
 'dun': 2319,
 'disturb': 2202,
 'liao': 3803,
 'thk': 6394,
 'lots': 3919,
 'aft': 779,
 'cupboard': 1971,
 'please': 4881,
 'service': 5615,
 'representative': 5318,
 '0800': 44,
 '169': 302,
 '6031': 523,
 'between': 1235,
 '10am': 254,
 '9pm': 674,
 '5000': 495,
 'tell': 6296,
 'address': 749,
 'checked': 1641,
 'heading': 3141,
 'drop': 2294,
 'stuff': 6095,
 'doing': 2236,
 'project': 5072,
 'frens': 2794,
 'lor': 3909,
 'yeah': 7161,
 'oz': 4690,
 'shitload': 5680,
 'calling': 1508,
 'everyone': 2491,
 'saying': 5518,
 'might': 4161,
 'cancer': 1527,
 'throat': 6412,
 'hurts': 3318,
 'talk': 6242,
 'answering': 908,
 'everyones': 2492,
 'calls': 1509,
 'babysitting': 1099,
 'monday': 4251,
 'walmart': 6870,
 'missing': 4197,
 'pray': 4995,
 'inshah': 3436,
 'allah': 838,
 'after': 780,
 'ah': 798,
 'den': 2089,
 'plus': 4893,
 'workin': 7081,
 'oso': 4650,
 'rite': 5390,
 'orchard': 4638,
 'other': 4651,
 'place': 4863,
 'im': 3366,
 'gloucesterroad': 2941,
 'uup': 6744,
 'sleep': 5788,
 'tired': 6446,
 'travel': 6555,
 'soon': 5884,
 'don': 2245,
 'about': 693,
 'anymore': 918,
 'tonight': 6498,
 'cried': 1940,
 'ì_': 7230,
 'pick': 4841,
 '530': 508,
 'al': 820,
 'moan': 4224,
 'thin': 6383,
 'goes': 2954,
 'wrong': 7113,
 'fault': 2606,
 'de': 2037,
 'arguments': 979,
 'fed': 2619,
 'himso': 3197,
 'bother': 1341,
 'hav': 3124,
 '2go': 369,
 'thanx': 6351,
 'xx': 7138,
 'per': 4789,
 'request': 5320,
 'melle': 4127,
 'oru': 4649,
 'minnaminunginte': 4180,
 'nurungu': 4530,
 'vettam': 6781,
 'set': 5619,
 'callertune': 1505,
 'callers': 1504,
 'press': 5021,
 'copy': 1877,
 'friends': 2802,
 'wishing': 7031,
 'family': 2583,
 'merry': 4141,
 'mas': 4067,
 'happy': 3104,
 'year': 7162,
 'advance': 763,
 'before': 1201,
 'noon': 4484,
 'shuhui': 5719,
 'change': 1611,
 'suntec': 6156,
 'steamboat': 6024,
 'noe': 4469,
 'ya': 7149,
 'very': 6780,
 'nice': 4445,
 'thursday': 6423,
 'alright': 850,
 'head': 3138,
 'few': 2637,
 'minutes': 4184,
 'meet': 4118,
 'dad': 1997,
 'went': 6956,
 'oredi': 4641,
 'hi': 3189,
 'mandy': 4041,
 'sullivan': 6139,
 'from': 2817,
 'hotmix': 3270,
 'fm': 2721,
 'chosen': 1686,
 'easter': 2345,
 'telephone': 6294,
 '09041940223': 152,
 '29': 359,
 '05': 14,
 'transferred': 6549,
 'else': 2392,
 'busy': 1463,
 'point': 4915,
 'figure': 2649,
 'may': 4094,
 'approve': 954,
 'panalam': 4708,
 'posts': 4962,
 'asking': 1012,
 'medical': 4114,
 'college': 1769,
 '7pm': 578,
 'forward': 2763,
 'any': 915,
 'training': 6541,
 'post': 4956,
 'weeks': 6942,
 'completely': 1805,
 'accommodation': 712,
 'various': 6762,
 'global': 2939,
 'locations': 3875,
 'phb1': 4821,
 'ph': 4818,
 '08700435505150p': 66,
 'sunday': 6149,
 'holiday': 3227,
 'flippin': 2703,
 'shit': 5679,
 'yet': 7173,
 'prefer': 5004,
 'days': 2033,
 'tues': 6598,
 'wed': 6930,
 'fri': 2797,
 'ìï': 7233,
 'ask': 1008,
 'slippers': 5799,
 'gone': 2965,
 'made': 4001,
 'payments': 4768,
 'much': 4318,
 'sorry': 5893,
 'fedex': 2620,
 'way': 6912,
 'la': 3708,
 'wana': 6873,
 'pei': 4781,
 'bf': 1239,
 'valuable': 6756,
 'situations': 5768,
 'first': 2681,
 'getting': 2913,
 'second': 5560,
 'loosing': 3907,
 'funeral': 2839,
 'audrey': 1052,
 'xam': 7129,
 'hall': 3073,
 'asked': 1010,
 'starting': 6004,
 'term': 6313,
 'answer': 905,
 'manage': 4035,
 'own': 4685,
 'hesitation': 3182,
 'lookin': 3900,
 'silently': 5738,
 'she': 5658,
 'intha': 3458,
 'ponnungale': 4931,
 'ipaditan': 3475,
 'wondarfull': 7064,
 'song': 5879,
 'wnt': 7055,
 'bmw': 1307,
 'urgently': 6721,
 'vry': 6830,
 'hv': 3322,
 'shortage': 5696,
 'lacs': 3714,
 'source': 5907,
 'arng': 985,
 'amt': 875,
 'prob': 5052,
 'jay': 3539,
 'sort': 5894,
 'fucking': 2826,
 'retard': 5350,
 'que': 5137,
 'pases': 4740,
 'un': 6652,
 'buen': 1440,
 'tiempo': 6431,
 'height': 3158,
 'confidence': 1825,
 'aeronautics': 770,
 'professors': 5065,
 'wer': 6958,
 'calld': 1501,
 'askd': 1009,
 'sit': 5761,
 'an': 878,
 'aeroplane': 771,
 'aftr': 785,
 'sat': 5503,
 'told': 6484,
 'dat': 2023,
 'plane': 4868,
 'ws': 7116,
 'their': 6363,
 'students': 6089,
 'dey': 2130,
 'hurried': 3314,
 'bt': 1432,
 'move': 4287,
 'mm': 4213,
 'feeling': 2624,
 'sleepy': 5793,
 'itself': 3504,
 'shall': 5646,
 'eat': 2347,
 'fo': 2724,
 'lunch': 3962,
 'senor': 5598,
 'cool': 1872,
 'gosh': 2982,
 'pain': 4701,
 'spose': 5966,
 'better': 1232,
 'company': 1794,
 'saibaba': 5469,
 'colany': 1759,
 'math': 4079,
 'quite': 5148,
 'long': 3894,
 'cos': 1884,
 'haven': 3127,
 'finish': 2669,
 'film': 2658,
 'entry': 2442,
 'into': 3459,
 '250': 348,
 'weekly': 6941,
 'comp': 1792,
 'word': 7076,
 'win': 7010,
 '80086': 586,
 'txttowin': 6629,
 'co': 1747,
 'uk': 6645,
 'did': 2145,
 'posted': 4960,
 'facebook': 2559,
 'settled': 5623,
 'wishin': 7030,
 'bloomberg': 1298,
 'center': 1599,
 '447797706009': 457,
 'why': 6993,
 'future': 2847,
 'http': 3294,
 'careers': 1547,
 'yup': 7212,
 'theory': 6372,
 'argument': 978,
 'wins': 7023,
 'situation': 5767,
 'loses': 3913,
 'person': 4805,
 'argue': 977,
 'kick': 3658,
 'always': 857,
 'correct': 1880,
 'email': 2396,
 'changed': 1612,
 'adult': 761,
 'content': 1851,
 'shortly': 5699,
 'anyway': 926,
 'shopping': 5692,
 'sis': 5758,
 'done': 2247,
 'oh': 4576,
 'little': 3856,
 'under': 6665,
 'weather': 6923,
 'coccooning': 1749,
 'balance': 1117,
 'currently': 1974,
 'maximize': 4092,
 '86688': 632,
 '150p': 291,
 'msg': 4301,
 'cc': 1586,
 '08718720201': 130,
 'hg': 3187,
 'suite342': 6136,
 '2lands': 373,
 'row': 5420,
 'w1j6hl': 6837,
 'still': 6038,
 'restaurant': 5343,
 'ill': 3364,
 'try': 6588,
 'usual': 6740,
 'iam': 3328,
 'fine': 2666,
 'most': 4276,
 'ive': 3509,
 'ever': 2487,
 'seen': 5577,
 'baby': 1097,
 'common': 1790,
 'howz': 3285,
 'down': 2262,
 'ystrday': 7204,
 'ice': 3337,
 'medicine': 4115,
 'brainless': 1375,
 'doll': 2240,
 'vehicle': 6773,
 'sariyag': 5500,
 'drive': 2288,
 'madoke': 4003,
 'barolla': 1137,
 'realise': 5211,
 'guy': 3052,
 'exams': 2513,
 'outta': 4673,
 'cars': 1562,
 'jus': 3608,
 'rain': 5162,
 'able': 691,
 'friday': 2798,
 'find': 2665,
 'alternative': 853,
 'yr': 7202,
 '2nights': 383,
 'lucky': 3956,
 'night': 4451,
 'uve': 6746,
 'invited': 3467,
 'xchat': 7131,
 'uks': 6647,
 'wildest': 7005,
 'msgrcvdhg': 4305,
 'ldn': 3764,
 '18yrs': 308,
 '2marrow': 374,
 'coming': 1784,
 'class': 1708,
 'wit': 7033,
 'different': 2157,
 'divorce': 2208,
 'lol': 3888,
 'here': 3175,
 'knew': 3684,
 'slept': 5794,
 'late': 3743,
 'yest': 7171,
 'wake': 6857,
 'woke': 7058,
 'tat': 6259,
 'yijue': 7178,
 'tot': 6522,
 'group': 3025,
 'mate': 4077,
 'meeting': 4120,
 'mah': 4012,
 'askin': 1011,
 'earlier': 2335,
 'mayb': 4095,
 'haf': 3063,
 'walk': 6861,
 'babe': 1094,
 'hours': 3273,
 'almost': 845,
 'internet': 3454,
 'explicit': 2541,
 'sex': 5628,
 'secs': 5567,
 'ring': 5378,
 '02073162414': 10,
 'costs': 1889,
 '20p': 334,
 'min': 4170,
 '09061790121': 196,
 'land': 3724,
 'line': 3833,
 '3030': 402,
 'dare': 2012,
 'unbelievable': 6654,
 'faglord': 2566,
 'hey': 3184,
 'looks': 3902,
 'kappa': 3628,
 'phone': 4829,
 'received': 5234,
 'reach': 5198,
 'already': 849,
 'wan': 6872,
 'tickets': 6429,
 'wiskey': 7032,
 'brandy': 1379,
 'rum': 5442,
 'gin': 2925,
 'beer': 1197,
 'vodka': 6817,
 'scotch': 5537,
 'shampain': 5648,
 'wine': 7016,
 'kudi': 3703,
 'yarasu': 7156,
 'dhina': 2133,
 'vaazhthukkal': 6748,
 'eyes': 2552,
 'philosophy': 4826,
 'great': 3013,
 'coco': 1752,
 'think': 6386,
 'passed': 4743,
 'ahold': 804,
 'anybody': 916,
 'throw': 6414,
 '83039': 605,
 '62735': 531,
 '450': 462,
 'break': 1386,
 'accommodationvouchers': 713,
 'terms': 6315,
 'conditions': 1822,
 'mustprovide': 4345,
 'which': 6981,
 '15541': 299,
 'fyi': 2849,
 'taking': 6239,
 'quick': 5144,
 'shower': 5710,
 'epsilon': 2449,
 'university': 6685,
 'southern': 5910,
 'california': 1495,
 'same': 5484,
 'question': 5141,
 'spend': 5938,
 'waiting': 6856,
 'ideal': 3344,
 'path': 4753,
 'appear': 940,
 'front': 2819,
 'us': 6727,
 'forget': 2752,
 'paths': 4754,
 'walking': 6865,
 'goodnight': 2975,
 'b4': 1087,
 'leave': 3776,
 'house': 3274,
 'these': 6375,
 'morphine': 4275,
 'thanks': 6346,
 'continued': 1857,
 'support': 6165,
 'enter': 2432,
 'in2': 3386,
 '100': 247,
 'president': 5018,
 'ans': 903,
 '80082': 585,
 'plz': 4895,
 'bslvyl': 1428,
 'via': 6782,
 'fullonsms': 2833,
 'fr': 2771,
 'dry': 2305,
 'spell': 5937,
 'season': 5557,
 'geeeee': 2891,
 'barely': 1134,
 'stand': 5994,
 'maid': 4016,
 'murderer': 4336,
 'coz': 1907,
 'man': 4034,
 'murdered': 4335,
 'th': 6342,
 'january': 3533,
 'public': 5106,
 'govt': 2992,
 'instituitions': 3444,
 'closed': 1727,
 'including': 3394,
 'stuck': 6086,
 'reason': 5219,
 'away': 1080,
 'til': 6438,
 'listen': 3849,
 'half': 3072,
 'hour': 3272,
 '6pm': 556,
 'right': 5373,
 'diet': 2153,
 'everyday': 2490,
 'cheat': 1636,
 'meant': 4108,
 'fatty': 2605,
 'brother': 1419,
 'genius': 2896,
 'pretty': 5027,
 'pussy': 5122,
 'fuck': 2824,
 'sake': 5471,
 'tallahassee': 6248,
 'freezing': 2791,
 'craving': 1922,
 'fml': 2722,
 'guoyang': 3049,
 'both': 1340,
 'piss': 4859,
 ...}

In [24]:
np.where(X_train_np!=0)

(array([   0,    0,    0, ..., 3899, 3899, 3899], dtype=int64),
 array([ 859,  988, 1177, ..., 4606, 6470, 6930], dtype=int64))

In [25]:
v.get_feature_names()[5417]

'round'

In [26]:
# v.vocabulary_

In [27]:
from sklearn.naive_bayes import MultinomialNB

model=MultinomialNB()
model.fit(X_train_cv,y_train)

MultinomialNB()

In [28]:
X_test_cv=v.transform(X_test)

In [23]:
# y_pred=model.predict(X_test_cv)

In [31]:
model.score(X_test_cv,y_test)

0.9820574162679426

In [32]:
from sklearn.metrics import classification_report

y_pred=model.predict(X_test_cv)

print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99      1469
           1       0.95      0.90      0.92       203

    accuracy                           0.98      1672
   macro avg       0.97      0.95      0.96      1672
weighted avg       0.98      0.98      0.98      1672

In [33]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]

emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1], dtype=int64)